# Generated by Django 3.2.19 on 2023-05-31 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_auto_20230531_1543'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='amount',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
